### ISSUE TITLE
Error with gpslogger

### ISSUE THREAD

**Issue by httpedo13** [home-assistant/home-assistant-polymer#1327]
I’m running HASS.IO 0.71.0. I was trying to configure gps logger but I get this error:

```
Error handling request
        Traceback (most recent call last):
          File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 385, in start
        resp = await self._request_handler(request)
          File "/usr/lib/python3.6/site-packages/aiohttp/web_app.py", line 338, in _handle
        resp = await handler(request)
          File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
        return await handler(request)
          File "/usr/lib/python3.6/site-packages/homeassistant/components/http/static.py", line 68, in staticresource_middleware
        return await handler(request)
          File "/usr/lib/python3.6/site-packages/homeassistant/components/http/real_ip.py", line 27, in real_ip_middleware
        return await handler(request)
          File "/usr/lib/python3.6/site-packages/homeassistant/components/http/ban.py", line 68, in ban_middleware
        return await handler(request)
          File "/usr/lib/python3.6/site-packages/homeassistant/components/http/auth.py", line 54, in auth_middleware
        return await handler(request)
          File "/usr/lib/python3.6/site-packages/homeassistant/components/http/view.py", line 98, in handle
        result = await result
          File "/usr/lib/python3.6/site-packages/homeassistant/components/device_tracker/gpslogger.py", line 85, in get
        accuracy = int(float(data['accuracy']))
        ValueError: could not convert string to float: '�C'
```

I followed the guide (https://www.home-assistant.io/components/device_tracker.gpslogger/ 4) and this is the url entered in the gpslogger app:

https://xxx.duckdns.org/api/gpslogger?latitude=%LAT&longitude=%LON&device=oneplus3&accuracy=%ACC&battery=%BATT&speed=%SPD&direction=%DIR&altitude=%ALT&provider=%PROV&activity=%ACT&api_password=yyy

I tried to leave only latitude, longitude and device:
https://xxx.duckdns.org/api/gpslogger?latitude=%LAT&longitude=%LON&device=oneplus3&api_password=yyy

But I get this error: “Could not parse gps value for oneplus3: (’%LAT’, ‘%LON’)”

**Comment by patchedsoul** [comment]
This should be opened in the main Home Assistant repo, not this one (polymer), which is targeted for frontend centric issues.

**Comment by c727** [comment]
^ + read the issue template instead of removing it
