### ISSUE TITLE
npm run js_dev fails

### ISSUE THREAD

**Issue by scottcmace** [home-assistant/home-assistant-polymer#219]
when  "npm run js_dev"  I get the following:

```
> home-assistant-polymer@1.0.0 js_dev /home/homeassistant/home-assistant/homeassistant/components/frontend/www_static/home-assistant-polymer
> script/gen-service-worker.js && npm run watch_ru_all

module.js:472
    throw err;
    ^

Error: Cannot find module 'sw-precache'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/homeassistant/home-assistant/homeassistant/components/frontend/www_static/home-assistant-polymer/script/gen-service-worker.js:15:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/root/.nvm/versions/node/v7.6.0/bin/node" "/root/.nvm/versions/node/v7.6.0/bin/npm" "run" "js_dev"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! home-assistant-polymer@1.0.0 js_dev: `script/gen-service-worker.js && npm run watch_ru_all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the home-assistant-polymer@1.0.0 js_dev script 'script/gen-service-worker.js && npm run watch_ru_all'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the home-assistant-polymer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     script/gen-service-worker.js && npm run watch_ru_all
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs home-assistant-polymer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls home-assistant-polymer
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/homeassistant/home-assistant/homeassistant/components/frontend/www_static/home-assistant-polymer/npm-debug.log
```

**Comment by scottcmace** [comment]
finally found missing dependency ...
