### ISSUE TITLE
lovelace  page keeps loading and loading

### ISSUE THREAD

**Issue by piepolitb** [home-assistant/home-assistant-polymer#2606]
**Home Assistant release with the issue:**

0.86.3

**Last working Home Assistant release (if known):**
0.84... maybe

**Browser and Operating System:**

Windows 10 with both Edge and Chrome

**Description of problem:**

While the classic frontend ui keeps working fine, lovelace doesn't anymore: it keeps loading and loading with the spinning circle.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
just this in the log
```
2019-01-28 10:16:54 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/http/static.py", line 66, in staticresource_middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/http/real_ip.py", line 34, in real_ip_middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/http/auth.py", line 99, in auth_middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/http/view.py", line 118, in handle
    result = await result
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/http/data_validator.py", line 47, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/hassio/auth.py", line 55, in post
    await self._check_login(data[ATTR_USERNAME], data[ATTR_PASSWORD])
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/hassio/auth.py", line 72, in _check_login
    await provider.async_validate_login(username, password)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/auth/providers/homeassistant.py", line 208, in async_validate_login
    self.data.validate_login, username, password)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/auth/providers/homeassistant.py", line 105, in validate_login
    for user in self.users:
  File "/usr/local/lib/python3.6/site-packages/homeassistant/auth/providers/homeassistant.py", line 93, in users
    return self._data['users']  # type: ignore
TypeError: 'NoneType' object is not subscriptable
```

**Comment by dohlin** [comment]
I am seeing these same symptoms, typically after my HA server (Ubuntu 18.04) has been up for a few days.  A reboot fixes things again for a little while.

**Comment by iantrich** [comment]
anyone still seeing this?
