### ISSUE TITLE
MPD media player error after upgrade

### ISSUE THREAD

**Issue by pzj101** [home-assistant/home-assistant-polymer#326]
Hi,

I've upgraded to 48.0 I get errors loading my mdp media player:

`2017-07-03 20:16:28 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform mpd
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/media_player/mpd.py", line 58, in setup_platform
    mpd_client = mpd.MPDClient()
AttributeError: 'module' object has no attribute 'MPDClient'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 164, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 372, in wait_for
    return fut.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/media_player/mpd.py", line 69, in setup_platform
    except mpd.CommandError as error:
AttributeError: 'module' object has no attribute 'CommandError'
`
Thanks

**Comment by balloob** [comment]
This issue is reported in the wrong repository. This is the frontend repository.
