### ISSUE TITLE
Developer Tools Inaccessible and Cannot Edit Entities Following Update to 0.98

### ISSUE THREAD

**Issue by Jonah1970** [home-assistant/home-assistant-polymer#3538]
**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**
0.97.2

**UI (States or Lovelace UI?):**

arch | x86_64
-- | --
dev | false
docker | true
hassio | false
os_name | Linux
python_version | 3.7.4
timezone | Europe/London
version | 0.97.2
virtualenv | false

![image](https://user-images.githubusercontent.com/53110372/63924533-5a1bcd80-ca40-11e9-9a74-c0580646b32e.png)

**Browser and Operating System:**

Firefox 68.0.2

**Description of problem:**

After updating to 0.98 I have observed the following anomolies:
1) At the top of Developer Tools/Info it shows "Home Assistant 0.98.0" however lower down it shows "version 0.97.2".
2) The Entity Registry is no longer editable i.e. click on any entity has no effect and no pop-up windows open.
3) Under Developer Tools only the Info and States windows are accessible, selecting Events, MQTT, Services, or Template causes a blue circle to be displayed continuously.  Clicking another options causes a brief message to be displayed "Error while loading page xxxxxx".

I have restarted Home Assistant several times and the problem persists.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

The Home Assistant log file is attached beow and seems typical of what I usually see in the first few seconds after a restart:

2019-08-29 10:28:35 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-08-29 10:29:52 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_start[L]>) at /usr/src/homeassistant/homeassistant/core.py:650
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 662, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 372, in async_run_job
    target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 185, in template_bsensor_startup
    self.async_check_state()
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 288, in async_check_state
    state = self._async_render()
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 231, in _async_render
    state = self._template.async_render().lower() == "true"
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 215, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: '<' not supported between instances of 'NoneType' and 'int'
2019-08-29 10:29:52 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback EventBus.async_listen_once.<locals>.onetime_listener(<Event homeassistant_start[L]>) at /usr/src/homeassistant/homeassistant/core.py:650
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 662, in onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 372, in async_run_job
    target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 185, in template_bsensor_startup
    self.async_check_state()
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 288, in async_check_state
    state = self._async_render()
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 231, in _async_render
    state = self._template.async_render().lower() == "true"
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 215, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: '<' not supported between instances of 'NoneType' and 'int'
2019-08-29 10:29:53 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback async_track_state_change.<locals>.state_change_listener(<Event state_...095276+01:00>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:77
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 96, in state_change_listener
    event.data.get("new_state"),
  File "/usr/src/homeassistant/homeassistant/core.py", line 372, in async_run_job
    target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 174, in template_bsensor_state_listener
    self.async_check_state()
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 288, in async_check_state
    state = self._async_render()
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 231, in _async_render
    state = self._template.async_render().lower() == "true"
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 215, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: '<' not supported between instances of 'NoneType' and 'int'
2019-08-29 10:29:54 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback async_track_state_change.<locals>.state_change_listener(<Event state_...029587+01:00>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:77
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 96, in state_change_listener
    event.data.get("new_state"),
  File "/usr/src/homeassistant/homeassistant/core.py", line 372, in async_run_job
    target(*args)
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 174, in template_bsensor_state_listener
    self.async_check_state()
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 288, in async_check_state
    state = self._async_render()
  File "/usr/src/homeassistant/homeassistant/components/template/binary_sensor.py", line 231, in _async_render
    state = self._template.async_render().lower() == "true"
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 215, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by Jonah1970** [comment]
This problem was resolved following a reboot of the Synology NAS that was hosting the HA Docker Container
