### ISSUE TITLE
installed version 0.48 don't work

### ISSUE THREAD

**Issue by claudius61** [home-assistant/home-assistant-polymer#401]
After installation  , the log wrote 👎 
2017-08-20 09:36:22 ERROR (Thread-1) [homeassistant.util.package] Unable to install package paho-mqtt==1.3.0: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/dist-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python3.4/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python3.4/dist-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/local/lib/python3.4/dist-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/local/lib/python3.4/dist-packages/pip/utils/__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/local/lib/python3.4/dist-packages/pip/utils/__init__.py", line 484, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
2017-08-20 09:36:22 ERROR (MainThread) [homeassistant.setup] Not initializing mqtt because could not install dependency paho-mqtt==1.3.0

**Comment by andrey-git** [comment]
0.48 is old and in any case this issue would belong to https://github.com/home-assistant/home-assistant

**Comment by claudius61** [comment]
the previous model was 0.47.1  on raspberry pi 3. Where is the problem?
Thank you for your assistance.

**Comment by claudius61** [comment]
I have the same problem with 0.49 , 0.50 , 0.51.1 !!

**Comment by fanaticDavid** [comment]
As pointed out by @andrey-git, this issue - relevant or not - belongs in https://github.com/home-assistant/home-assistant . This repository is for the Home Assistant frontend (web interface).
