### ISSUE TITLE
Netatmo camera.py error Presence URL is none

### ISSUE THREAD

**Issue by dietlman** [home-assistant/home-assistant-polymer#5031]
## The problem

I get the following error after integration of Netatmo Presence camera. in Lovelace it shows no picture of preview of the livestream, the error in log is decribed below. Integration of Netatmo worked fine, the other Netatmo Sensors are working perfect.

Developer Tools
Welcome/Presence VPN URL is None
7:40:30 AM – netatmo (ERROR) - message first occurred at 7:40:00 AM and shows up 8 times
Update for camera.netatmo_dw24 fails
7:39:24 AM – components/netatmo/camera.py (ERROR)
Update of camera.netatmo_dw24 is taking over 10 seconds
7:39:07 AM – __main__.py (WARNING)
Error doing job: Task exception was never retrieved
7:35:35 AM – components/ring/__init__.py (ERROR) - message first occurred at 7:34:36 AM and shows up 12 times
Error doing job: Future exception was never retrieved
7:35:30 AM – components/ring/__init__.py (ERROR)
Time out fetching Ring active dings data
7:34:35 AM – ring (WARNING)
Time out fetching Ring device data
7:34:34 AM – ring (WARNING)
Time out fetching Ring history data for device 4c2498891ab5
7:34:34 AM – ring (WARNING)
Error handling request
7:25:47 AM – components/ring/camera.py (ERROR)
FFmpeg isn't running!
7:25:47 AM – components/ring/camera.py (WARNING)
FFmpeg fails
7:25:46 AM – /usr/local/lib/python3.7/site-packages/haffmpeg/core.py (ERROR)
Update of camera.eingangstur is taking over 10 seconds
7:21:22 AM – __main__.py (WARNING) - message first occurred at 7:13:15 AM and shows up 3 times
Error executing service <ServiceCall frontend.reload_themes (c:1c26a71bd8664323b91e105d79bc9d23)>
7:20:47 AM – components/frontend/__init__.py (ERROR)
Error executing service <ServiceCall frontend.reload_themes (c:b45abe1e29464728be80626c7fd7ddb9)>
7:20:18 AM – components/frontend/__init__.py (ERROR)
Error executing service <ServiceCall frontend.reload_themes (c:890df3e94a184b99a167627c3825c314)>
7:14:06 AM – components/frontend/__init__.py (ERROR)
Login attempt or request with invalid authentication from 192.168.1.169
7:13:34 AM – http (WARNING)
HMGeneric.getValue: OPERATING_VOLTAGE on 000A5A49A198FD:0 Exception: <Fault -5: 'Unknown Parameter for value key: OPERATING_VOLTAGE'>
7:13:17 AM – components/homematic/entity.py (WARNING) - message first occurred at 7:13:16 AM and shows up 2 times
HMGeneric.getValue: OPERATING_VOLTAGE on 000A5A49A1A896:0 Exception: <Fault -5: 'Unknown Parameter for value key: OPERATING_VOLTAGE'>
7:13:17 AM – components/homematic/entity.py (WARNING) - message first occurred at 7:13:16 AM and shows up 2 times
HMGeneric.getValue: WORKING on 0008D8A9A701A3:4 Exception: <Fault -5: 'Unknown Parameter for value key: WORKING'>
7:13:16 AM – components/homematic/entity.py (WARNING)
Unable to obtain the vehicle charger state for WAUZZZFY9H2013888: 400, message='Bad Request', url='https://msg.volkswagen.de/fs-car/bs/batterycharge/v1/Audi/Austria/vehicles/WAUZZZFY9H2013888/charger
7:13:08 AM – custom_components/audiconnect/audi_connect_account.py (ERROR)
Unable to obtain the vehicle climatisation state for WAUZZZFY9H2013888: 400, message='Bad Request', url='https://msg.volkswagen.de/fs-car/bs/climatisation/v1/Audi/Austria/vehicles/WAUZZZFY9H2013888/climater
7:13:08 AM – custom_components/audiconnect/audi_connect_account.py (ERROR)
Unable to update the vehicle position of WAUZZZFY9H2013888: 400, message='Bad Request', url='https://msg.volkswagen.de/fs-car/bs/cf/v1/Audi/Austria/vehicles/WAUZZZFY9H2013888/position
7:13:08 AM – custom_components/audiconnect/audi_connect_account.py (ERROR)
Unable to obtain the vehicle status report of WAUZZZFY9H2013888: 400, message='Bad Request', url='https://msg.volkswagen.de/fs-car/bs/vsr/v1/Audi/Austria/vehicles/WAUZZZFY9H2013888/status
7:13:07 AM – custom_components/audiconnect/audi_connect_account.py (ERROR)
Setup of homematic is taking over 10 seconds.
7:13:06 AM – __main__.py (WARNING)
netatmo: Error on device update!
7:13:06 AM – Binary sensor (ERROR)
netatmo: Error on device update!
7:13:06 AM – Binary sensor (ERROR)
netatmo: Error on device update!
7:13:06 AM – Binary sensor (ERROR)
netatmo: Error on device update!
7:13:06 AM – Binary sensor (ERROR)
Found malformed XML at http://172.17.0.2:8080/upnp: <!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>
7:13:05 AM – /usr/local/lib/python3.7/site-packages/pywemo/ssdp.py (ERROR)
Error fetching Home Assistant update data:
7:13:01 AM – Updater (ERROR)
Could not contact Home Assistant Update to check for updates
7:13:01 AM – Updater (ERROR)
You are using a custom integration for fronius_inverter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
7:12:55 AM – loader.py (WARNING)
 
Log Details (ERROR)
Logger: homeassistant.helpers.entity
First occured: 7:39:24 AM (1 occurences)
Last logged: 7:39:24 AM

Update for camera.netatmo_dw24 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 326, in recv_into
    raise timeout("The read operation timed out")
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.netatmo.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/camera.py", line 223, in update
    self._data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/netatmo/camera.py", line 282, in update
    self.camera_data = pyatmo.CameraData(self.auth, size=100)
  File "/usr/local/lib/python3.7/site-packages/pyatmo/camera.py", line 28, in __init__
    resp = self.authData.post_request(url=_GETHOMEDATA_REQ, params=postParams)
  File "/usr/local/lib/python3.7/site-packages/pyatmo/auth.py", line 119, in post_request
    resp = query(url, params, timeout, 3)
  File "/usr/local/lib/python3.7/site-packages/pyatmo/auth.py", line 114, in query
    return self._oauth.post(url=url, data=params, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests_oauthlib/oauth2_session.py", line 516, in request
    method, url, headers=headers, data=data, **kwargs
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.netatmo.com', port=443): Read timed out. (read timeout=30)
Successfully saved

**Comment by vasseurf** [comment]
Hello. Same problem here. Just moved from 0.104 to 0.106 and use the new netatmo auth via integrations page. Sensors are working OK. But cameras (Presence & Welcome) show no picture (but exist as entities). Same error : "[homeassistant.components.netatmo.camera] Welcome/Presence VPN URL is None"

**Comment by dietlman** [comment]
Good to know that I am not the only one having this issue. Looks like there is a bug in the integration.

**Comment by cgtobi** [comment]
Please use the right bug tracker for this and fill out the issue template over at https://github.com/home-assistant/core/issues.

**Comment by egoetz-zz** [comment]
Hello. Got exactly the same problem here!
